spring.application.name=shopcart

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=shopcart-database

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=sa

spring.cache.redis.time-to-live=60000
